export const ACTION_ADD_PERSON = 'ACTION_ADD_PERSON';
export const ACTION_UPDATE_PERSON = 'ACTION_UPDATE_PERSON';
export const ACTION_REMOVE_PERSON = 'ACTION_REMOVE_PERSON';
export const ACTION_SORT = 'ACTION_SORT';